### ISSUE TITLE
jsonld.InvalidUrl: Dereferencing a URL did not result in a valid JSON-LD object.

### ISSUE THREAD

**Issue by rlzijdeman** [LinkedPasts/linked-places#21]
Hi, 

when using the example .jsonld files in the playground, the interpreter calls out that the URL to the context does not exist. I think for both the jsonld files [1,2] the context file ought to be version `1.1` rather than `1.3` (in `"@context": "https://raw.githubusercontent.com/LinkedPasts/linked-places/master/linkedplaces-context-v1.1.jsonld"`).

[1] https://github.com/LinkedPasts/linked-places/blob/master/data/lugares_13k_20190429.jsonld
[2] https://github.com/LinkedPasts/linked-places/blob/master/data/topostext_20190429.jsonld

**Comment by kgeographer** [comment]
Corrections merged, thank you
